#!/usr/bin/env bash
# This script configures an Ubuntu server as followed
# **** localhost resolves to 127.0.0.2
# **** facebok.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost"> ~/hosts.new
echo "8.8.8.8		facebook.com"> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
